# generated by datamodel-codegen:
#   filename:  output.json
#   timestamp: 2024-07-25T07:39:09+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Fragment(BaseModel):
    url: str
    duration: float


class DownloaderOptions(BaseModel):
    http_chunk_size: int


class Format(BaseModel):
    format_id: str
    format_note: Optional[str] = None
    ext: str
    protocol: str
    acodec: Optional[str] = None
    vcodec: str
    url: str
    width: Optional[int] = None
    height: Optional[int] = None
    fps: Optional[float] = None
    rows: Optional[int] = None
    columns: Optional[int] = None
    fragments: Optional[List[Fragment]] = None
    resolution: str
    aspect_ratio: Optional[float]
    filesize_approx: Optional[int] = None
    http_headers: Dict[str, Any]
    audio_ext: str
    video_ext: str
    vbr: float
    abr: Optional[float]
    tbr: Optional[float]
    format: str
    format_index: None = None
    manifest_url: Optional[str] = None
    language: Optional[str] = None
    preference: None = None
    quality: Optional[float] = None
    has_drm: Optional[bool] = None
    source_preference: Optional[int] = None
    asr: Optional[int] = None
    filesize: Optional[int] = None
    audio_channels: Optional[int] = None
    language_preference: Optional[int] = None
    dynamic_range: Optional[str] = None
    container: Optional[str] = None
    downloader_options: Optional[DownloaderOptions] = None


class Thumbnail(BaseModel):
    url: str
    preference: int
    id: str
    height: Optional[int] = None
    width: Optional[int] = None
    resolution: Optional[str] = None


class AfItem(BaseModel):
    ext: str
    url: str
    name: str


class AkItem(BaseModel):
    ext: str
    url: str
    name: str


class SqItem(BaseModel):
    ext: str
    url: str
    name: str


class AmItem(BaseModel):
    ext: str
    url: str
    name: str


class ArItem(BaseModel):
    ext: str
    url: str
    name: str


class HyItem(BaseModel):
    ext: str
    url: str
    name: str


class A(BaseModel):
    ext: str
    url: str
    name: str


class AyItem(BaseModel):
    ext: str
    url: str
    name: str


class AzItem(BaseModel):
    ext: str
    url: str
    name: str


class BnItem(BaseModel):
    ext: str
    url: str
    name: str


class EuItem(BaseModel):
    ext: str
    url: str
    name: str


class BeItem(BaseModel):
    ext: str
    url: str
    name: str


class BhoItem(BaseModel):
    ext: str
    url: str
    name: str


class B(BaseModel):
    ext: str
    url: str
    name: str


class BgItem(BaseModel):
    ext: str
    url: str
    name: str


class MyItem(BaseModel):
    ext: str
    url: str
    name: str


class CaItem(BaseModel):
    ext: str
    url: str
    name: str


class CebItem(BaseModel):
    ext: str
    url: str
    name: str


class ZhHan(BaseModel):
    ext: str
    url: str
    name: str


class ZhHantItem(BaseModel):
    ext: str
    url: str
    name: str


class CoItem(BaseModel):
    ext: str
    url: str
    name: str


class HrItem(BaseModel):
    ext: str
    url: str
    name: str


class C(BaseModel):
    ext: str
    url: str
    name: str


class DaItem(BaseModel):
    ext: str
    url: str
    name: str


class DvItem(BaseModel):
    ext: str
    url: str
    name: str


class NlItem(BaseModel):
    ext: str
    url: str
    name: str


class EnOrigItem(BaseModel):
    ext: str
    url: str
    name: str


class EnItem(BaseModel):
    ext: str
    url: str
    name: str


class EoItem(BaseModel):
    ext: str
    url: str
    name: str


class EtItem(BaseModel):
    ext: str
    url: str
    name: str


class EeItem(BaseModel):
    ext: str
    url: str
    name: str


class FilItem(BaseModel):
    ext: str
    url: str
    name: str


class FiItem(BaseModel):
    ext: str
    url: str
    name: str


class FrItem(BaseModel):
    ext: str
    url: str
    name: str


class GlItem(BaseModel):
    ext: str
    url: str
    name: str


class LgItem(BaseModel):
    ext: str
    url: str
    name: str


class KaItem(BaseModel):
    ext: str
    url: str
    name: str


class DeItem(BaseModel):
    ext: str
    url: str
    name: str


class ElItem(BaseModel):
    ext: str
    url: str
    name: str


class GnItem(BaseModel):
    ext: str
    url: str
    name: str


class GuItem(BaseModel):
    ext: str
    url: str
    name: str


class HtItem(BaseModel):
    ext: str
    url: str
    name: str


class HaItem(BaseModel):
    ext: str
    url: str
    name: str


class HawItem(BaseModel):
    ext: str
    url: str
    name: str


class IwItem(BaseModel):
    ext: str
    url: str
    name: str


class HiItem(BaseModel):
    ext: str
    url: str
    name: str


class HmnItem(BaseModel):
    ext: str
    url: str
    name: str


class HuItem(BaseModel):
    ext: str
    url: str
    name: str


class I(BaseModel):
    ext: str
    url: str
    name: str


class IgItem(BaseModel):
    ext: str
    url: str
    name: str


class IdItem(BaseModel):
    ext: str
    url: str
    name: str


class GaItem(BaseModel):
    ext: str
    url: str
    name: str


class ItItem(BaseModel):
    ext: str
    url: str
    name: str


class JaItem(BaseModel):
    ext: str
    url: str
    name: str


class JvItem(BaseModel):
    ext: str
    url: str
    name: str


class KnItem(BaseModel):
    ext: str
    url: str
    name: str


class KkItem(BaseModel):
    ext: str
    url: str
    name: str


class KmItem(BaseModel):
    ext: str
    url: str
    name: str


class RwItem(BaseModel):
    ext: str
    url: str
    name: str


class KoItem(BaseModel):
    ext: str
    url: str
    name: str


class KriItem(BaseModel):
    ext: str
    url: str
    name: str


class KuItem(BaseModel):
    ext: str
    url: str
    name: str


class KyItem(BaseModel):
    ext: str
    url: str
    name: str


class LoItem(BaseModel):
    ext: str
    url: str
    name: str


class LaItem(BaseModel):
    ext: str
    url: str
    name: str


class LvItem(BaseModel):
    ext: str
    url: str
    name: str


class LnItem(BaseModel):
    ext: str
    url: str
    name: str


class LtItem(BaseModel):
    ext: str
    url: str
    name: str


class LbItem(BaseModel):
    ext: str
    url: str
    name: str


class MkItem(BaseModel):
    ext: str
    url: str
    name: str


class MgItem(BaseModel):
    ext: str
    url: str
    name: str


class M(BaseModel):
    ext: str
    url: str
    name: str


class MlItem(BaseModel):
    ext: str
    url: str
    name: str


class MtItem(BaseModel):
    ext: str
    url: str
    name: str


class MiItem(BaseModel):
    ext: str
    url: str
    name: str


class MrItem(BaseModel):
    ext: str
    url: str
    name: str


class MnItem(BaseModel):
    ext: str
    url: str
    name: str


class NeItem(BaseModel):
    ext: str
    url: str
    name: str


class NsoItem(BaseModel):
    ext: str
    url: str
    name: str


class NoItem(BaseModel):
    ext: str
    url: str
    name: str


class NyItem(BaseModel):
    ext: str
    url: str
    name: str


class OrItem(BaseModel):
    ext: str
    url: str
    name: str


class OmItem(BaseModel):
    ext: str
    url: str
    name: str


class P(BaseModel):
    ext: str
    url: str
    name: str


class FaItem(BaseModel):
    ext: str
    url: str
    name: str


class PlItem(BaseModel):
    ext: str
    url: str
    name: str


class PtItem(BaseModel):
    ext: str
    url: str
    name: str


class PaItem(BaseModel):
    ext: str
    url: str
    name: str


class QuItem(BaseModel):
    ext: str
    url: str
    name: str


class RoItem(BaseModel):
    ext: str
    url: str
    name: str


class RuItem(BaseModel):
    ext: str
    url: str
    name: str


class SmItem(BaseModel):
    ext: str
    url: str
    name: str


class SaItem(BaseModel):
    ext: str
    url: str
    name: str


class GdItem(BaseModel):
    ext: str
    url: str
    name: str


class SrItem(BaseModel):
    ext: str
    url: str
    name: str


class SnItem(BaseModel):
    ext: str
    url: str
    name: str


class SdItem(BaseModel):
    ext: str
    url: str
    name: str


class SiItem(BaseModel):
    ext: str
    url: str
    name: str


class SkItem(BaseModel):
    ext: str
    url: str
    name: str


class SlItem(BaseModel):
    ext: str
    url: str
    name: str


class SoItem(BaseModel):
    ext: str
    url: str
    name: str


class StItem(BaseModel):
    ext: str
    url: str
    name: str


class E(BaseModel):
    ext: str
    url: str
    name: str


class SuItem(BaseModel):
    ext: str
    url: str
    name: str


class SwItem(BaseModel):
    ext: str
    url: str
    name: str


class SvItem(BaseModel):
    ext: str
    url: str
    name: str


class TgItem(BaseModel):
    ext: str
    url: str
    name: str


class TaItem(BaseModel):
    ext: str
    url: str
    name: str


class TtItem(BaseModel):
    ext: str
    url: str
    name: str


class TeItem(BaseModel):
    ext: str
    url: str
    name: str


class ThItem(BaseModel):
    ext: str
    url: str
    name: str


class TiItem(BaseModel):
    ext: str
    url: str
    name: str


class T(BaseModel):
    ext: str
    url: str
    name: str


class TrItem(BaseModel):
    ext: str
    url: str
    name: str


class TkItem(BaseModel):
    ext: str
    url: str
    name: str


class UkItem(BaseModel):
    ext: str
    url: str
    name: str


class UrItem(BaseModel):
    ext: str
    url: str
    name: str


class UgItem(BaseModel):
    ext: str
    url: str
    name: str


class UzItem(BaseModel):
    ext: str
    url: str
    name: str


class ViItem(BaseModel):
    ext: str
    url: str
    name: str


class CyItem(BaseModel):
    ext: str
    url: str
    name: str


class FyItem(BaseModel):
    ext: str
    url: str
    name: str


class XhItem(BaseModel):
    ext: str
    url: str
    name: str


class YiItem(BaseModel):
    ext: str
    url: str
    name: str


class YoItem(BaseModel):
    ext: str
    url: str
    name: str


class ZuItem(BaseModel):
    ext: str
    url: str
    name: str


class AutomaticCaptions(BaseModel):
    af: List[AfItem]
    ak: List[AkItem]
    sq: List[SqItem]
    am: List[AmItem]
    ar: List[ArItem]
    hy: List[HyItem]
    as_: List[A] = Field(..., alias="as")
    ay: List[AyItem]
    az: List[AzItem]
    bn: List[BnItem]
    eu: List[EuItem]
    be: List[BeItem]
    bho: List[BhoItem]
    bs: List[B]
    bg: List[BgItem]
    my: List[MyItem]
    ca: List[CaItem]
    ceb: List[CebItem]
    zh_Hans: List[ZhHan] = Field(..., alias="zh-Hans")
    zh_Hant: List[ZhHantItem] = Field(..., alias="zh-Hant")
    co: List[CoItem]
    hr: List[HrItem]
    cs: List[C]
    da: List[DaItem]
    dv: List[DvItem]
    nl: List[NlItem]
    en_orig: List[EnOrigItem] = Field(..., alias="en-orig")
    en: List[EnItem]
    eo: List[EoItem]
    et: List[EtItem]
    ee: List[EeItem]
    fil: List[FilItem]
    fi: List[FiItem]
    fr: List[FrItem]
    gl: List[GlItem]
    lg: List[LgItem]
    ka: List[KaItem]
    de: List[DeItem]
    el: List[ElItem]
    gn: List[GnItem]
    gu: List[GuItem]
    ht: List[HtItem]
    ha: List[HaItem]
    haw: List[HawItem]
    iw: List[IwItem]
    hi: List[HiItem]
    hmn: List[HmnItem]
    hu: List[HuItem]
    is_: List[I] = Field(..., alias="is")
    ig: List[IgItem]
    id: List[IdItem]
    ga: List[GaItem]
    it: List[ItItem]
    ja: List[JaItem]
    jv: List[JvItem]
    kn: List[KnItem]
    kk: List[KkItem]
    km: List[KmItem]
    rw: List[RwItem]
    ko: List[KoItem]
    kri: List[KriItem]
    ku: List[KuItem]
    ky: List[KyItem]
    lo: List[LoItem]
    la: List[LaItem]
    lv: List[LvItem]
    ln: List[LnItem]
    lt: List[LtItem]
    lb: List[LbItem]
    mk: List[MkItem]
    mg: List[MgItem]
    ms: List[M]
    ml: List[MlItem]
    mt: List[MtItem]
    mi: List[MiItem]
    mr: List[MrItem]
    mn: List[MnItem]
    ne: List[NeItem]
    nso: List[NsoItem]
    no: List[NoItem]
    ny: List[NyItem]
    or_: List[OrItem] = Field(..., alias="or")
    om: List[OmItem]
    ps: List[P]
    fa: List[FaItem]
    pl: List[PlItem]
    pt: List[PtItem]
    pa: List[PaItem]
    qu: List[QuItem]
    ro: List[RoItem]
    ru: List[RuItem]
    sm: List[SmItem]
    sa: List[SaItem]
    gd: List[GdItem]
    sr: List[SrItem]
    sn: List[SnItem]
    sd: List[SdItem]
    si: List[SiItem]
    sk: List[SkItem]
    sl: List[SlItem]
    so: List[SoItem]
    st: List[StItem]
    es: List[E]
    su: List[SuItem]
    sw: List[SwItem]
    sv: List[SvItem]
    tg: List[TgItem]
    ta: List[TaItem]
    tt: List[TtItem]
    te: List[TeItem]
    th: List[ThItem]
    ti: List[TiItem]
    ts: List[T]
    tr: List[TrItem]
    tk: List[TkItem]
    uk: List[UkItem]
    ur: List[UrItem]
    ug: List[UgItem]
    uz: List[UzItem]
    vi: List[ViItem]
    cy: List[CyItem]
    fy: List[FyItem]
    xh: List[XhItem]
    yi: List[YiItem]
    yo: List[YoItem]
    zu: List[ZuItem]


class Chapter(BaseModel):
    start_time: float
    title: str
    end_time: float


class RequestedFormat(BaseModel):
    format_id: str
    format_index: None = None
    url: str
    manifest_url: Optional[str] = None
    tbr: float
    ext: str
    fps: Optional[float]
    protocol: str
    preference: None
    quality: float
    has_drm: bool
    width: Optional[int]
    height: Optional[int]
    vcodec: str
    acodec: str
    dynamic_range: Optional[str]
    source_preference: int
    resolution: str
    aspect_ratio: Optional[float]
    http_headers: Dict[str, Any]
    video_ext: str
    audio_ext: str
    abr: float
    vbr: float
    format: str
    asr: Optional[int] = None
    filesize: Optional[int] = None
    format_note: Optional[str] = None
    audio_channels: Optional[int] = None
    filesize_approx: Optional[int] = None
    language: Optional[str] = None
    language_preference: Optional[int] = None
    container: Optional[str] = None
    downloader_options: Optional[DownloaderOptions] = None


class InfoModel(BaseModel):
    id: str
    title: str
    formats: List[Format]
    thumbnails: List[Thumbnail]
    thumbnail: str
    description: str
    channel_id: str
    channel_url: str
    duration: int
    view_count: int
    average_rating: None
    age_limit: int
    webpage_url: str
    categories: List[str]
    tags: List[str]
    playable_in_embed: bool
    live_status: str
    release_timestamp: None
    field_format_sort_fields: List[str] = Field(..., alias="_format_sort_fields")
    automatic_captions: AutomaticCaptions
    subtitles: Dict[str, Any]
    comment_count: int
    chapters: List[Chapter]
    heatmap: List
    like_count: int
    channel: str
    channel_follower_count: int
    channel_is_verified: bool
    uploader: str
    uploader_id: str
    uploader_url: str
    upload_date: str
    timestamp: int
    availability: str
    original_url: str
    webpage_url_basename: str
    webpage_url_domain: str
    extractor: str
    extractor_key: str
    playlist: None
    playlist_index: None
    display_id: str
    fulltitle: str
    duration_string: str
    release_year: None
    is_live: bool
    was_live: bool
    requested_subtitles: None
    field_has_drm: None = Field(..., alias="_has_drm")
    epoch: int
    requested_formats: List[RequestedFormat]
    format: str
    format_id: str
    ext: str
    protocol: str
    language: str
    format_note: str
    filesize_approx: int
    tbr: float
    width: int
    height: int
    resolution: str
    fps: float
    dynamic_range: str
    vcodec: str
    vbr: float
    stretched_ratio: None
    aspect_ratio: float
    acodec: str
    abr: float
    asr: int
    audio_channels: int

    # generate a fromjson function
    @classmethod
    def from_json(cls, json_str: str) -> "InfoModel":
        return cls.model_validate_json(json_str)
